services:
  guzzle_client:
      class: 'GuzzleHttp\Client'

  coinhive_captcha.validator:
      class: 'CoinhiveBundle\Validator\IsTrueValidator'
      arguments:
          - '@guzzle_client'
          - ''
      tags:
          - { name: 'validator.constraint_validator', alias: 'coinhive_captcha_validator' }

  coinhive_captcha.form:
      class: 'CoinhiveBundle\Form\CoinHiveCaptchaType'
      arguments:
          - ''
      tags:
          - { name: 'form.type' }

  coinhive_miner.twig:
      class: 'CoinhiveBundle\Twig\Extensions\CoinhiveMinerExtension'
      arguments:
          - ''
      tags:
          - { name: 'twig.extension' }
